#!/usr/bin/env python3
"""Generate h3_unicode_tables.c for the portable C11 h3 tokenizer.

Data source: this interpreter's unicodedata module. Tables emitted:

  * h3_unicode_letters    - ranges of code points in categories Lu Ll Lt Lm Lo
  * h3_unicode_numbers    - ranges of code points in categories Nd Nl No
  * h3_unicode_ccc        - ranges with a non-zero canonical combining class
  * h3_unicode_decompose  - canonical (non-compatibility) decomposition pairs
  * h3_unicode_compose    - (left, right) -> composite composition pairs

Letters/numbers cover the full UCS range (the ICU-backed Objective-C
implementation classifies astral code points too). The NFC tables cover the
BMP only; Hangul composition/decomposition is algorithmic and lives in
h3_tokenizer.c. The White_Space property is a short fixed list and is also
hardcoded in h3_tokenizer.c.

A pair (left, right) is composable to C exactly when C has a canonical
two-part decomposition [left, right] and NFC(left + right) == C; checking
with unicodedata.normalize automatically excludes singleton decompositions,
non-starter decompositions and everything in CompositionExclusions.txt.
"""

import sys
import unicodedata

BMP = 0x10000
FULL = 0x110000

LETTER_CATEGORIES = frozenset(("Lu", "Ll", "Lt", "Lm", "Lo"))
NUMBER_CATEGORIES = frozenset(("Nd", "Nl", "No"))


def category_ranges(categories, limit):
    """Sorted, merged [first, last] ranges whose category is in categories."""
    out = []
    start = None
    for cp in range(limit):
        if unicodedata.category(chr(cp)) in categories:
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, limit - 1))
    return out


def ccc_ranges(limit):
    """Sorted, merged [first, last, ccc] ranges with non-zero combining class."""
    out = []
    cp = 0
    while cp < limit:
        value = unicodedata.combining(chr(cp))
        if not value:
            cp += 1
            continue
        end = cp
        while end + 1 < limit and unicodedata.combining(chr(end + 1)) == value:
            end += 1
        out.append((cp, end, value))
        cp = end + 1
    return out


def decomposition_tables(limit):
    """(decompose, compose): canonical decomposition pairs and their inverse."""
    decompose = []
    compose = []
    for cp in range(limit):
        raw = unicodedata.decomposition(chr(cp))
        if not raw or raw.startswith("<"):
            continue
        parts = [int(item, 16) for item in raw.split()]
        if not 1 <= len(parts) <= 2:
            raise RuntimeError("unexpected decomposition for U+%04X" % cp)
        left = parts[0]
        right = parts[1] if len(parts) > 1 else 0
        decompose.append((cp, left, right))
        if right and unicodedata.normalize("NFC", chr(left) + chr(right)) == chr(cp):
            compose.append((left, right, cp))
    compose.sort()
    return decompose, compose


def emit_ranges(out, name, rows):
    out.append("const h3_unicode_range %s[] = {" % name)
    for first, last in rows:
        out.append("    {UINT32_C(0x%04x), UINT32_C(0x%04x)}," % (first, last))
    out.append("};")
    out.append("const size_t %s_count =" % name)
    out.append("    sizeof(%s) / sizeof(%s[0]);" % (name, name))
    out.append("")


def main():
    letters = category_ranges(LETTER_CATEGORIES, FULL)
    numbers = category_ranges(NUMBER_CATEGORIES, FULL)
    ccc = ccc_ranges(BMP)
    decompose, compose = decomposition_tables(BMP)

    out = [
        "/* Generated by tools/generate_unicode_tables.py; do not edit.",
        " * Unicode data version %s (Python unicodedata). */" %
        unicodedata.unidata_version,
        "",
        '#include "h3_unicode_tables.h"',
        "",
    ]
    emit_ranges(out, "h3_unicode_letters", letters)
    emit_ranges(out, "h3_unicode_numbers", numbers)

    out.append("const h3_unicode_ccc_range h3_unicode_ccc[] = {")
    for first, last, value in ccc:
        out.append("    {UINT32_C(0x%04x), UINT32_C(0x%04x), %d}," %
                   (first, last, value))
    out.append("};")
    out.append("const size_t h3_unicode_ccc_count =")
    out.append("    sizeof(h3_unicode_ccc) / sizeof(h3_unicode_ccc[0]);")
    out.append("")

    out.append("const h3_unicode_decompose_entry h3_unicode_decompose[] = {")
    for cp, left, right in decompose:
        out.append("    {UINT32_C(0x%04x), UINT32_C(0x%04x), UINT32_C(0x%04x)}," %
                   (cp, left, right))
    out.append("};")
    out.append("const size_t h3_unicode_decompose_count =")
    out.append("    sizeof(h3_unicode_decompose) / sizeof(h3_unicode_decompose[0]);")
    out.append("")

    out.append("const h3_unicode_compose_entry h3_unicode_compose[] = {")
    for left, right, cp in compose:
        out.append("    {UINT32_C(0x%04x), UINT32_C(0x%04x), UINT32_C(0x%04x)}," %
                   (left, right, cp))
    out.append("};")
    out.append("const size_t h3_unicode_compose_count =")
    out.append("    sizeof(h3_unicode_compose) / sizeof(h3_unicode_compose[0]);")
    out.append("")

    with open(sys.argv[1] if len(sys.argv) > 1 else "h3_unicode_tables.c",
              "w", encoding="utf-8") as stream:
        stream.write("\n".join(out))
    print("letters=%d numbers=%d ccc=%d decompose=%d compose=%d" %
          (len(letters), len(numbers), len(ccc), len(decompose), len(compose)))


if __name__ == "__main__":
    main()
